# Generated by Django 5.0.2 on 2024-03-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_accept',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_send',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
